### ISSUE TITLE
Missing Data

### ISSUE THREAD

**Issue by Timeofsand** [Lyve1981/GrowattUsbModbus#3]
Hello, everyone.

I installed the project and it was relatively easy to set up. However, I don't know exactly how to proceed because I don't know that much about Modbus.

My problem is I don't have all the data I would like in Node-Red. I miss the current power. Here is an example of what I get:

<details><summary>My Output</summary>

pvstatus: 9
pvpowerin: 0
pv1voltage: 0
pv1current: 0
pv1watt: 0
pv2voltage: 0
pv2current: 0
pv2watt: 0
pvpowerout: 0
pvfrequentie: 5001
pvgridvoltage: 4060
pvgridcurrent: 0
pvgridpower: 344
pvgridvoltage2: 4187
pvgridcurrent2: 0
pvgridpower2: 0
pvgridvoltage3: 4125
pvgridcurrent3: 0
pvgridpower3: 0
eactoday: 28
pvenergytoday: 28
eactotal: 162
totworktime: 579968
epv1today: 36
epv1total: 194
epv2today: 0
epv2total: 0
epvtotal: 194
pvtemperature: 255
pvipmtemperature: 237
pvboosttemp: 235
bat_dsp: 11
eacharge_today: 2
eacharge_total: 7
batterytype: 1
uwsysworkmode: 9
systemfaultword0: 0
systemfaultword1: 0
systemfaultword2: 0
systemfaultword3: 33348
systemfaultword4: 32
systemfaultword5: 0
systemfaultword6: 0
systemfaultword7: 0
pdischarge1: 0
p1charge1: 0
vbat: 0
SOC: 0
pactouserr: 3800
pactousertot: 3800
pactogridr: 0
pactogridtot: 0
plocaloadr: 3800
plocaloadtot: 3800
spdspstatus: 9
spbusvolt: 38
etouser_tod: 99
etouser_tot: 477
etogrid_tod: 14
etogrid_tot: 47
edischarge1_tod: 0
edischarge1_tot: 0
eharge1_tod: 0
eharge1_tot: 0
elocalload_tod: 117
elocalload_tot: 611
datalogserial: "ModBus2USB"
pvserial: "TJJ4CG300D"

</details>

I use the GROWATT SPH 4000TL3 BRA-UP

Thank You

**Comment by Lyve1981** [comment]
I see you just closed it, but for others for future reference: pvstatus: 9 indicates that the inverter is running in Bypass mode
