### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by schwaigi** [Lyve1981/GrowattUsbModbus#6]
Hy
allways get a Code error:

`C:\Users\Schwaigi\Downloads\GrowattUsbModbus-main` (2)\GrowattUsbModbus\GrowattUsbModbus.ino: In function 'bool sendError(const ArduinoJson6201_F1::StaticJsonDocument<1024>&, const char*)':
C:\Users\Schwaigi\Downloads\GrowattUsbModbus-main (2)\GrowattUsbModbus\GrowattUsbModbus.ino:95:1: error: no return statement in function returning non-void [-Werror=return-type]
   95 | }
      | ^
C:\Users\Schwaigi\Downloads\GrowattUsbModbus-main (2)\GrowattUsbModbus\GrowattUsbModbus.ino: In function 'bool sendError(const char*)':
C:\Users\Schwaigi\Downloads\GrowattUsbModbus-main (2)\GrowattUsbModbus\GrowattUsbModbus.ino:99:1: error: no return statement in function returning non-void [-Werror=return-type]
   99 | }
      | ^
cc1plus.exe: some warnings being treated as errors

exit status 1

Compilation error: no return statement in function returning non-void [-Werror=return-type]`

**Comment by ilikebeer** [comment]
HI 
i have the same Problem 

Some Solution?

**Comment by frankewi** [comment]
Just got the same error,

both functions
bool sendError(const StaticJsonDocument<1024>& request, const char* error)
bool sendError(const char* error)
won't return anything:

change: add a "return" in both functions:

bool sendError(const StaticJsonDocument<1024>& request, const char* error)
{
	return sendError(&request, error);

}
bool sendError(const char* error)
{
	return sendError(nullptr, error);
}

**Comment by ilikebeer** [comment]
Hi,

i got the same Error, but i deleted all of them.
Here the modifid Code it works fine 

[GrowattUsbModbus_insalled.zip](https://github.com/Lyve1981/GrowattUsbModbus/files/11191648/GrowattUsbModbus_insalled.zip)

**Comment by Lyve1981** [comment]
fixed via PR #9
